# Generated by Django 3.2 on 2022-10-08 14:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscriptions',
            field=models.ManyToManyField(related_name='subscribtions', to=settings.AUTH_USER_MODEL),
        ),
    ]
